// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yvewvqqcwduwauihdsxf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl2ZXd2cXFjd2R1d2F1aWhkc3hmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3NTc1ODAsImV4cCI6MjA3MzMzMzU4MH0.lOSLV2OOttkoOiTHOjy8zw3iFhL6p9WW7gGrym3kEuo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});